# Theme settings
doks:
    baseurl: https://mmrc.app/
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: Modern Model Railways Control
            image:
        nav:
            - item_name: Introduction
              item_url: '#'
            - item_name: Layouth connection
              item_url: '#'
            - item_name: Entities
              item_url: '#'
            - item_name: Automation
              item_url: '#'
    footer:
        content:
            logo:
                text: Modern Model Railways Control
                image:
            copyright: This project is open source. Help us in [github](https://github.com/ricard2k/mmrc)
        social_list:
            # - network_name: facebook
            #   profile_url: '#'
            # - network_name: twitter
            #   profile_url: '#'
            # - network_name: instagram
            #   profile_url: '#'
            - network_name: youtube
              profile_url: '#'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
