# Theme settings
doks:
    baseurl: https://mmrc.app/
    color_theme: green # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: Modern Model Railroad Control
            image:
        nav:
            - item_name: WHAT IS MMRC? 
              item_url: 'about/'
            - item_name: Layout connection
              item_url: 'connections/'
            - item_name: Tables
              item_url: 'tables/'
            - item_name: Automation
              item_url: 'automation/'
    footer:
        content:
            logo:
                text: Modern Model Railroad Control
                image:
            copyright: 'This project is open source. Help us in <a href="https://github.com/ricard2k/mmrc">github</a>'
        social_list:
            # - network_name: facebook
            #   profile_url: '#'
            # - network_name: twitter
            #   profile_url: '#'
            # - network_name: instagram
            #   profile_url: '#'
            - network_name: youtube
              profile_url: '#'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
