name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18.2

      - name: Install dependencies
        run: npm install

      - name: Build angular frontend
        run: npm run build

      - name: Build electron
        run: npm run electron:make

      - name: Publish electron
        run: npm run electron:publish
