name: Build/release

on: push

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  NOTORIZE_APPLE_ID: ${{secrets.NOTORIZE_APPLE_ID}}
  NOTORIZE_APPLE_ID_PASSWORD: ${{secrets.NOTORIZE_APPLE_ID_PASSWORD}}

jobs:
  release:
    runs-on: ${{ matrix.os }}

    permissions:
      deployments: write

    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18.2

      - name: Install dependencies
        run: npm install

      - name: Build angular frontend
        run: npm run build

      - name: Build electron typescript
        run: npm run electron:buildts

      - name: Publish electron
        run: npm run electron:publish
